# Generated by Django 4.1.3 on 2022-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(default='', upload_to='apply/'),
            preserve_default=False,
        ),
    ]
